import assert from 'node:assert/strict';
import {defaultChartState} from '../src/history';
import {mapFunction,matchFunctions,remapChart} from '../src/preservation';
import type {FlowGraph,FlowNode} from '../src/types';
const node=(id:string,code:string,kind='process'):FlowNode=>({id,label:code,kind,line:1,start_byte:1,end_byte:2,comments:[],source_identity:code});
const graph=(nodes:FlowNode[]):FlowGraph=>({nodes,edges:[],diagnostics:[]});
const before=graph([node('a','x=1'),node('b','y=2')]);
const after=graph([node('c','x=1'),node('d','y=3')]);
const state=defaultChartState();
state.edits={'function:10:overview':{a:{natural:'Set x',annotation:'Keep note'},b:{natural:'Set y'}}};
state.captions={'function:10:detail':{a:'Initialise x',b:'Initialise y'}};
state.hiddenBoxes={'function:10':['a']};state.functionPositions={'function:10':{x:90,y:100}};
const mapped=remapChart(state,[mapFunction('function:10','function:2',before,after)]);
assert.deepEqual(mapped.edits,{'function:2:overview':{c:{natural:'Set x',annotation:'Keep note'}}});
assert.deepEqual(mapped.captions,{'function:2:detail':{c:'Initialise x'}});
assert.deepEqual(mapped.hiddenBoxes,{'function:2':['c']});
assert.deepEqual(mapped.functionPositions,{'function:2':{x:90,y:100}});
assert.equal(state.edits['function:10:overview'].b.natural,'Set y');
const commentOnly=remapChart(state,[mapFunction('function:10','function:0',before,graph([node('n','x=1'),node('m','y=2')]))]);
assert.equal(commentOnly.edits['function:0:overview'].m.natural,'Set y');
assert.equal(matchFunctions([{id:'old',name:'sum',line:1,identity:'signature'}],[{id:'new',name:'sum',line:2,identity:'signature'}])[0][1].id,'new');
assert.equal(matchFunctions([{id:'old',name:'sum',line:1}],[{id:'new',name:'sum',line:2},{id:'overload',name:'sum',line:3}]).length,0);
const loopOld={...node('loop','old body','loop'),header_identity:'same condition'};
const loopNew={...node('newloop','changed body','loop'),header_identity:'same condition'};
const loopMap=mapFunction('old','new',graph([loopOld]),graph([loopNew]));
assert.equal(loopMap.detail.get('loop'),'newloop');assert.equal(loopMap.overview.has('loop'),false);
assert.equal(mapFunction('old','new',graph([node('a','same'),node('b','same')]),graph([node('c','same')])).detail.size,0);
assert.equal(mapFunction('old','new',graph([node('a','same'),node('b','same')]),graph([node('c','same'),node('d','same')])).detail.get('b'),'d','comment-only changes retain even repeated boxes when entire graph is unchanged');
console.log('PASS: stable code retains labels, notes and layout; changed or ambiguous boxes invalidate only their edits');
